### PR TITLE
Feature/friendship

### PR DESCRIPTION
**Pull request by Mohamed-js**
- Made associations between the user and the friendship model.
- Made associations for creator and receiver of friend request.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Mohammed atef wajih abu-waly mahmoud & Andy Castañeda Ramos** 
Good job with your first submission for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] Add both unit and integration tests
- [x] When the user is logged, the root page should show the comments from the current user and all its friends.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @Mohamed-js  and @andresporras3423, Great job! 👏  Both of you have done well on this project.

> Well done on the update done on your ReadMe file 👏 Even going ahead to deploy the project already, nice!

Let's make a couple of changes, and we will be done.

- [x] You have 5 failed tests cases, kindly fix them. You should try using [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers) for your unit tests, you will love it. 
Screen Shot 2021-03-15 at 6 04 28 PM

- [x] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
See affected files below:

> `frienships/_friend_request.html.erb`
> `frienships/index.html.erb`
> `layouts/application.html.erb`
> `users/index.html.erb`
> `users/show.html.erb`

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 

- [x] Ruby on Rails uses the MVC pattern, meaning Model handles most of the business logic, views for presentation  and controller connects both. There should be NO application logic in the views nor helpers (no Post.new, Comment.create, current_user.friends.find_by(...)...). Everything connected with data processing should be encapsulated in models and used in controllers. Kindly move the following methods to your Model and call them from there.
```ruby
def my_friends
    requested_friends = current_user.friendships.map(&:receiver)
    accepted_friends = current_user.friendships.map(&:creator)
    requested_friends.compact + accepted_friends.compact
  end

  def friend?(_user)
    requested_friends = current_user.friendships.map { |friendship| friendship.receiver if friendship.status == false }
    accepted_friends = current_user.friendships.map { |friendship| friendship.creator if friendship.status == true }
    requested_friends.compact + accepted_friends.compact
  end

  def row_creator(user)
    f1 = Friendship.find_by(creator_id: user.creator_id, receiver_id: user.receiver_id)
    f2 = Friendship.find_by(creator_id: user.receiver_id, receiver_id: user.creator_id)

    f1.id < f2.id
  end
```

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by uryelah** [comment]
Hi @Mohamed-js, sadly I'll have to mark this submission as invalid.

It was submitted with for the milestone Deploy, but the contents of this PR pertain to the milestone Friendship V2, please make sure you submit the correct milestone to the corresponding form in your student dashboard :-)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Mohamed-js and @afcastaneda223
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

- [x] Please work on the last TSE's suggestion.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by whiz25 — APPROVED** [review]
## Approved 👏🏿 
Amazing work. You managed to make the requested changes. Your PR meets the minimum requirements for approval.
Merge and proceed to the next milestone.


### Martin Afani
#### Slack: whiz25

**Pull request merged**
